api_platform:
    title: 'Stock Management API'
    version: '1.0.0'
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        pagination_enabled: true
        pagination_client_enabled: true
        pagination_items_per_page: 10
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    oauth:
        enabled: false