version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PHP_MEMORY_LIMIT: 512M
      PHP_OPCACHE_ENABLE: 1
      PHP_OPCACHE_REVALIDATE_FREQ: 0
    volumes:
      - ./:/var/www/html:cached
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html:cached
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stockGestion
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_INNODB_BUFFER_POOL_SIZE: 256M
    ports:
      - "3307:3306"  # Réajout du port
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:  # Déclaration du volume nommé