version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PHP_MEMORY_LIMIT: 512M
      PHP_OPCACHE_ENABLE: 1
      PHP_OPCACHE_REVALIDATE_FREQ: 0
      COMPOSER_MEMORY_LIMIT: -1
    volumes:
      - ./:/var/www/html:cached  # On garde juste celui-ci pour l'instant
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.75'

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html:cached
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  mysql:
    image: mysql:8.0
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --innodb-buffer-pool-size=256M
      --innodb-log-buffer-size=32M
      --innodb-file-per-table=1
      --innodb-flush-method=O_DIRECT
      --innodb-flush-log-at-trx-commit=0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stockGestion
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql:cached
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: